config/routes.rb
Rails.application.routes.draw do

  devise_for :views
  devise_for :users
  get 'pages/about'

  get 'sessions/new'

  resources :posts
  resources :users

  root 'posts#index'

  get 'new', to: 'posts#new'

  # Users
  get '/signup', to: 'users#new'
  get '/signup', to: 'users#create'

  # Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Pages
  get '/about', to: 'pages#about'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true,
  length: { minimum: 2 }, uniqueness: true
  validates :body, presence: true, allow_nil: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def User.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page], :per_page=> 10).order('id DESC')
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"

    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all.order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Thanks for signing up!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
  end

  def update
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Droid+Sans|Open+Sans' %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to "Blog", root_path %></li>
    <li><%= link_to "About", "#" %></li>
  </ul>

  <ul id="dropdown1" class="dropdown-content">
    <li><a href="https://github.com/sunnlamp">Github</a></li>
    <li><a href="https://www.instagram.com/sunnlamp/">Instagram</a></li>
    <li><a href="https://www.linkedin.com/in/rogelio-zamudio-b78180133?trk=hp-identity-name">LinkedIn</a></li>
    <li><a href="mailto:yeyozaz@gmail.com">Email</a></li>
  </ul>

  <nav>
    <div class="nav-wrapper">
        <ul class="items right hide-on-med-down">
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Social
            <i class="material-icons right"></i></a></li>
          <li><a class="dropdown-button" href="#!" data-activates="dropdown2">Website
            <i class="material-icons right"></i></a></li>
          <% if !logged_in? %>
              <li id="login">
                <%= link_to "Log In", login_path, class: "btn" %>
              </li>
          <% end %>
          <% if logged_in? %>
            <li><%= link_to "Log Out", logout_path, class: "btn", method: :delete %></li>
            <% if current_user.admin? %>
              <li><%= link_to "New Post", new_post_path, class: "btn" %></li>
            <% end %>
          <% end %>
        </ul>
    </div>
  </nav>

  <div class="main-content row">

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/posts/_edit_form.html.erb
<div class="row">
  <div class="container">
    <%= form_for(:post, url: posts_path) do |f| %>
      <% if @post.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@post.errors.count, "error") %> prevented
          this post from saving.</h2>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </div>
      <% end %>
      <%= f.label :title %>
      </br>
      <%= f.text_field :title %>
      </br>
      <%= f.label :body %>
      </br>
      <%= f.text_field :body, as: :text, class: "materialize-textarea" %>
      </br>
      <%= f.submit "Post Edits", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col s12">
    <%= form_for(:post, url: posts_path) do |f| %>

      <% if @post.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@post.errors.count, "error") %> prevented
          this post from saving.</h2>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </div>
      <% end %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :body %>
      <%= f.text_field :body, as: :text, class: "materialize-textarea", id: "textarea1" %>

      <%= f.submit "Create Post", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="wrapper">
  <h1>Edit Post</h1>
  <%= render 'edit_form' %>
</div>

app/views/posts/index.html.erb
<p>All Posts</p>
<%= will_paginate @post %>

<%= will_paginate %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1 class="title"><%= @post.title %></h1>
<p class="date">
  Submitted <%= time_ago_in_words(@post.created_at) %> ago.
</p>

<p class="body">
  <%= @post.body %>
</p>

<%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-primary" %>
<%= link_to "Delete Post", post_path(@post), class: "btn btn-primary",
    method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/users/new.html.erb
<h1>Sign up</h1>
  <div class="row">
    <%= form_for(@user) do |f| %>

      <div class="input-field">
        <%= f.text_field :name, autofocus: true, class: "validate", placeholder: "Name" %>
      </div>
      <div class="input-field">
        <%= f.email_field :email, autofocus: true, class: "validate", placeholder: "Email" %>
      </div>
      <div class="input-field">
        <%= f.password_field :password, :id => "password", placeholder: "Password", class: "validate" %>
      </div>
      <div class="input-field">
        <%= f.password_field :password_confirmation, :id => "password_confirmation", placeholder: "Password Confirmation", class: "validate" %>
      </div>

      <%= f.submit "Create account", class: "btn" %>
    <% end %>
  </div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>